In [1]:
from pathlib import Path

import pandas as pd
import numpy as np


PROJECT_DIR = Path(
    r"C:\Users\acer\Desktop\ProgettoTesi"
)

RESULTS_DIR = (
    PROJECT_DIR
    / "risultati"
)

TURN_PATH = (
    RESULTS_DIR
    / "profilazione_acustica"
    / "turni_con_label_acustica.csv"
)

EMBEDDING_DIR = (
    RESULTS_DIR
    / "embedding_multimodali_turn_level"
)

EMBEDDING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print("PROJECT_DIR:", PROJECT_DIR)
print("TURN_PATH:", TURN_PATH)
print("EMBEDDING_DIR:", EMBEDDING_DIR)

print("\nEsiste TURN_PATH:", TURN_PATH.exists())

PROJECT_DIR: C:\Users\acer\Desktop\ProgettoTesi
TURN_PATH: C:\Users\acer\Desktop\ProgettoTesi\risultati\profilazione_acustica\turni_con_label_acustica.csv
EMBEDDING_DIR: C:\Users\acer\Desktop\ProgettoTesi\risultati\embedding_multimodali_turn_level

Esiste TURN_PATH: True

In [2]:
turn_df = pd.read_csv(
    TURN_PATH
)


print(
    "Shape:",
    turn_df.shape
)

print(
    "Pazienti:",
    turn_df["patient_id"].nunique()
)

print(
    "Turni:",
    len(turn_df)
)

print(
    "Trascrizioni non vuote:",
    turn_df["transcript"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)


print(
    "\nPrime colonne:"
)

print(
    turn_df.columns.tolist()[:40]
)

Shape: (3825, 108)
Pazienti: 90
Turni: 3825
Trascrizioni non vuote: 3710

Prime colonne:
['patient_id', 'recording_id', 'nome_file', 'canale', 'turn_index', 'turn_id', 'start_seconds', 'end_seconds', 'turn_duration_seconds', 'patient_speakers', 'n_diar_segments_merged', 'preceding_role', 'preceding_speaker', 'response_latency_seconds', 'audio_path_turn', 'peak_amplitude', 'clipping_ratio', 'f0_p5', 'f0_p25', 'f0_median', 'f0_p75', 'f0_p95', 'f0_mean', 'f0_std', 'f0_iqr', 'f0_range_p95_p5', 'voiced_f0_frames', 'rms_mean', 'rms_std', 'rms_p5', 'rms_p95', 'non_silent_duration_seconds', 'speech_activity_ratio', 'speech_activity_percent', 'silence_ratio', 'internal_pause_count', 'internal_pause_total_seconds', 'internal_pause_mean_seconds', 'internal_pause_median_seconds', 'internal_pause_max_seconds']

17.3 — Audit degli embedding audio già presenti

In [3]:
embedding_folders = [
    RESULTS_DIR / "embedding_audio",
    RESULTS_DIR / "embedding_audio_padding",
    RESULTS_DIR / "classificazione_dn4_10s_30"
]


for folder in embedding_folders:
    print(
        "\n=========================================="
    )
    print(
        "CARTELLA:",
        folder
    )
    print(
        "Esiste:",
        folder.exists()
    )
    if folder.exists():
        csv_files = sorted(
            folder.glob("*.csv")
        )
        for file in csv_files:
            print(
                " -",
                file.name
            )

==========================================
CARTELLA: C:\Users\acer\Desktop\ProgettoTesi\risultati\embedding_audio
Esiste: True
 - coordinate_pca.csv
 - coordinate_umap.csv
 - correlazioni_esplorative.csv
 - embeddings_whisper_small.csv
 - metadata_embedding.csv

==========================================
CARTELLA: C:\Users\acer\Desktop\ProgettoTesi\risultati\embedding_audio_padding
Esiste: True
 - confronto_full_vs_valid.csv
 - coordinate_pca_full.csv
 - coordinate_pca_valid_only.csv
 - coordinate_umap_full.csv
 - coordinate_umap_valid_only.csv
 - correlazioni_esplorative_full_vs_valid.csv
 - metadata_embedding_padding_test.csv
 - silhouette_durata_padding.csv
 - verifica_padding_input.csv

==========================================
CARTELLA: C:\Users\acer\Desktop\ProgettoTesi\risultati\classificazione_dn4_10s_30
Esiste: True
 - metadata_clip_embedding.csv
 - metadata_pazienti_classificazione.csv
 - metriche_oof.csv
 - metriche_per_fold.csv
 - predizioni_oof_per_paziente.csv
 - riepilogo_cv.csv

17.4 — Struttura degli embedding Whisper precedenti

In [4]:
OLD_WHISPER_PATH = (
    RESULTS_DIR
    / "embedding_audio"
    / "embeddings_whisper_small.csv"
)


print(
    "Esiste:",
    OLD_WHISPER_PATH.exists()
)


if OLD_WHISPER_PATH.exists():
    old_whisper = pd.read_csv(
        OLD_WHISPER_PATH
    )

    print(
        "\nShape:",
        old_whisper.shape
    )

    print(
        "\nPrime 30 colonne:"
    )

    print(
        old_whisper.columns.tolist()[:30]
    )

    display(
        old_whisper.head(3)
    )

Esiste: True

Shape: (18, 769)

Prime 30 colonne:
['clip_id', 'emb_0000', 'emb_0001', 'emb_0002', 'emb_0003', 'emb_0004', 'emb_0005', 'emb_0006', 'emb_0007', 'emb_0008', 'emb_0009', 'emb_0010', 'emb_0011', 'emb_0012', 'emb_0013', 'emb_0014', 'emb_0015', 'emb_0016', 'emb_0017', 'emb_0018', 'emb_0019', 'emb_0020', 'emb_0021', 'emb_0022', 'emb_0023', 'emb_0024', 'emb_0025', 'emb_0026', 'emb_0027', 'emb_0028']

,clip_id,emb_0000,emb_0001,emb_0002,emb_0003,emb_0004,emb_0005,emb_0006,emb_0007,emb_0008,...,emb_0758,emb_0759,emb_0760,emb_0761,emb_0762,emb_0763,emb_0764,emb_0765,emb_0766,emb_0767
0,ID121.StudioRuggi__10s__0003,0.263098,-0.101657,3.206217,0.159911,-0.188504,0.061799,-0.040628,0.018271,0.054182,...,0.078815,0.073413,0.179286,0.170338,-0.200587,-0.049647,0.065576,0.369620,-0.046162,-0.107388
1,ID121.StudioRuggi__10s__0005,0.116559,-0.277846,3.425232,-0.087034,0.095657,0.168641,-0.099322,0.000727,0.077634,...,0.331586,0.284323,-0.019607,0.026119,-0.084868,-0.116575,-0.054902,0.329387,-0.025719,-0.334034
2,ID121.StudioRuggi__10s__0013,0.195481,0.000182,3.464634,0.246730,0.139047,0.101642,0.088279,-0.076000,-0.095029,...,-0.021139,0.076776,-0.314319,0.160162,0.014389,-0.242278,0.206209,0.221018,0.234960,-0.084973

17.5 — Colonne utili per ricostruire il segmento audio

In [5]:
AUDIO_KEYWORDS = [
    "audio",
    "wav",
    "file",
    "path",
    "start",
    "end",
    "time",
    "channel",
    "recording",
    "turn"
]


audio_related_columns = [
    col
    for col in turn_df.columns
    if any(
        keyword in col.lower()
        for keyword in AUDIO_KEYWORDS
    )
]


print(
    "Colonne potenzialmente utili:"
)

for col in audio_related_columns:
    print("-", col)


display(
    turn_df[
        audio_related_columns
    ].head(10)
)

Colonne potenzialmente utili:
- recording_id
- nome_file
- turn_index
- turn_id
- start_seconds
- end_seconds
- turn_duration_seconds
- audio_path_turn

,recording_id,nome_file,turn_index,turn_id,start_seconds,end_seconds,turn_duration_seconds,audio_path_turn
0,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,0,ID1.StudioRuggi-006__patient_turn_0000,1.567,3.338,1.771000,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
1,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,1,ID1.StudioRuggi-006__patient_turn_0001,5.903,7.878,1.975062,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
2,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,2,ID1.StudioRuggi-006__patient_turn_0002,14.375,30.338,15.963000,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
3,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,3,ID1.StudioRuggi-006__patient_turn_0003,33.410,37.240,3.830000,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
4,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,5,ID1.StudioRuggi-006__patient_turn_0005,43.180,45.037,1.857063,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
5,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,8,ID1.StudioRuggi-006__patient_turn_0008,55.988,63.768,7.780000,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
6,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,9,ID1.StudioRuggi-006__patient_turn_0009,66.502,67.632,1.130000,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
7,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,10,ID1.StudioRuggi-006__patient_turn_0010,68.240,69.877,1.637063,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
8,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,11,ID1.StudioRuggi-006__patient_turn_0011,70.957,76.897,5.940000,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...
9,ID1.StudioRuggi-006,ID1.StudioRuggi-006.wav,12,ID1.StudioRuggi-006__patient_turn_0012,80.002,87.190,7.188063,c:\Users\acer\Desktop\ProgettoTesi\risultati\f...

17.6 — Dataset comune audio + testo

In [6]:
multimodal_df = turn_df.copy()

multimodal_df["transcript_clean"] = (
    multimodal_df["transcript"]
    .fillna("")
    .astype(str)
    .str.strip()
)

multimodal_df = (
    multimodal_df[
        multimodal_df["transcript_clean"].ne("")
    ]
    .copy()
    .reset_index(drop=True)
)


print("Turni multimodali:", len(multimodal_df))
print("Pazienti:", multimodal_df["patient_id"].nunique())

print(
    "Turni esclusi per trascrizione assente:",
    len(turn_df) - len(multimodal_df)
)

print(
    "Turn ID univoci:",
    multimodal_df["turn_id"].nunique()
)

Turni multimodali: 3710
Pazienti: 90
Turni esclusi per trascrizione assente: 115
Turn ID univoci: 3710

17.7 — Verifica disponibilità audio dei 3710 turni

In [7]:
from pathlib import Path


multimodal_df["audio_exists"] = (
    multimodal_df["audio_path_turn"]
    .apply(
        lambda x: Path(str(x)).exists()
    )
)


print(
    "Audio presenti:",
    int(multimodal_df["audio_exists"].sum()),
    "/",
    len(multimodal_df)
)

print(
    "Audio mancanti:",
    int((~multimodal_df["audio_exists"]).sum())
)


if (~multimodal_df["audio_exists"]).any():

    display(
        multimodal_df.loc[
            ~multimodal_df["audio_exists"],
            [
                "patient_id",
                "turn_id",
                "audio_path_turn"
            ]
        ].head(20)
    )

Audio presenti: 3710 / 3710
Audio mancanti: 0

17.8 — Verifica librerie

In [8]:
import importlib.util


packages = [
    "torch",
    "transformers",
    "sentence_transformers",
    "librosa",
    "soundfile"
]


for package in packages:

    print(
        f"{package:25s}",
        bool(
            importlib.util.find_spec(package)
        )
    )

torch                     True
transformers              True
sentence_transformers     False
librosa                   True
soundfile                 True

In [11]:
import torch


print("PyTorch:", torch.__version__)
print("CUDA disponibile:", torch.cuda.is_available())

if torch.cuda.is_available():

    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )

PyTorch: 2.13.0+cpu
CUDA disponibile: False

In [12]:
import sys
import subprocess

print("Python del notebook:")
print(sys.executable)

subprocess.check_call(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "sentence-transformers"
    ]
)

print("\n✓ sentence-transformers installato.")

Python del notebook:
c:\Users\acer\Desktop\ProgettoTesi\.venv\Scripts\python.exe

✓ sentence-transformers installato.

In [ ]:
from sentence_transformers import SentenceTransformer

import sentence_transformers

print(
    "sentence-transformers:",
    sentence_transformers.__version__
)

print("✓ Import riuscito.")

17.10 — Embedding testuali turn-level

In [13]:
from sentence_transformers import SentenceTransformer
import torch


TEXT_MODEL_NAME = (
    "sentence-transformers/"
    "paraphrase-multilingual-MiniLM-L12-v2"
)


device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


print("Modello:", TEXT_MODEL_NAME)
print("Device:", device)


text_model = SentenceTransformer(
    TEXT_MODEL_NAME,
    device=device
)

Modello: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Device: cpu

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

c:\Users\acer\Desktop\ProgettoTesi\.venv\lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\acer\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.89k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  471MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 9.08MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

17.11 — Estrazione embedding testuali

In [14]:
texts = (
    multimodal_df[
        "transcript_clean"
    ]
    .tolist()
)

text_embeddings = text_model.encode(
    texts,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=False
)


print(
    "Shape embedding testuali:",
    text_embeddings.shape
)

print(
    "NaN:",
    np.isnan(text_embeddings).sum()
)

print(
    "Inf:",
    np.isinf(text_embeddings).sum()
)

Batches:   0%|          | 0/58 [00:00<?, ?it/s]

Shape embedding testuali: (3710, 384)
NaN: 0
Inf: 0

17.12 — Salvataggio embedding testuali

In [15]:
TEXT_EMBEDDING_PATH = (
    EMBEDDING_DIR
    / "embedding_testuali_multilingual_minilm.npy"
)

TEXT_METADATA_PATH = (
    EMBEDDING_DIR
    / "metadata_turni_multimodali.csv"
)


np.save(
    TEXT_EMBEDDING_PATH,
    text_embeddings
)


multimodal_df[
    [
        "patient_id",
        "recording_id",
        "turn_id",
        "turn_index",
        "turn_duration_seconds",
        "audio_path_turn",
        "transcript_clean"
    ]
].to_csv(
    TEXT_METADATA_PATH,
    index=False
)


print(
    "Embedding:",
    TEXT_EMBEDDING_PATH
)

print(
    "Metadata:",
    TEXT_METADATA_PATH
)

print(
    "\nFile embedding esiste:",
    TEXT_EMBEDDING_PATH.exists()
)

print(
    "File metadata esiste:",
    TEXT_METADATA_PATH.exists()
)

Embedding: C:\Users\acer\Desktop\ProgettoTesi\risultati\embedding_multimodali_turn_level\embedding_testuali_multilingual_minilm.npy
Metadata: C:\Users\acer\Desktop\ProgettoTesi\risultati\embedding_multimodali_turn_level\metadata_turni_multimodali.csv

File embedding esiste: True
File metadata esiste: True

17.13 — Audit audio prima degli embedding Whisper

In [16]:
from pathlib import Path
import soundfile as sf


# ------------------------------------------------------------
# Esistenza dei file
# ------------------------------------------------------------

multimodal_df["audio_exists"] = (
    multimodal_df["audio_path_turn"]
    .apply(lambda x: Path(str(x)).exists())
)


print(
    "Audio presenti:",
    int(multimodal_df["audio_exists"].sum()),
    "/",
    len(multimodal_df)
)

print(
    "Audio mancanti:",
    int((~multimodal_df["audio_exists"]).sum())
)


# ------------------------------------------------------------
# Distribuzione durata
# ------------------------------------------------------------

print("\nDurata turni multimodali:")

display(
    multimodal_df[
        "turn_duration_seconds"
    ]
    .describe(
        percentiles=[
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
    .to_frame()
    .round(3)
)


print(
    "\nTurni > 30 secondi:",
    int(
        (
            multimodal_df[
                "turn_duration_seconds"
            ] > 30
        ).sum()
    )
)

print(
    "Turni > 60 secondi:",
    int(
        (
            multimodal_df[
                "turn_duration_seconds"
            ] > 60
        ).sum()
    )
)


# ------------------------------------------------------------
# Sample rate / canali su un campione di 100 file
# ------------------------------------------------------------

sample_audio = (
    multimodal_df[
        multimodal_df["audio_exists"]
    ]
    .sample(
        n=min(100, int(multimodal_df["audio_exists"].sum())),
        random_state=42
    )
)


audio_info = []

for path in sample_audio["audio_path_turn"]:

    with sf.SoundFile(str(path)) as f:

        audio_info.append(
            {
                "sample_rate": f.samplerate,
                "channels": f.channels
            }
        )


audio_info_df = pd.DataFrame(audio_info)


print("\nSample rate:")
print(
    audio_info_df[
        "sample_rate"
    ].value_counts()
)


print("\nNumero canali:")
print(
    audio_info_df[
        "channels"
    ].value_counts()
)

Audio presenti: 3710 / 3710
Audio mancanti: 0

Durata turni multimodali:

       turn_duration_seconds
count               3710.000
mean                   2.990
std                    3.801
min                    0.320
50%                    1.738
75%                    3.337
90%                    6.328
95%                    9.857
99%                   20.037
max                   57.881

Turni > 30 secondi: 6
Turni > 60 secondi: 0

Sample rate:
sample_rate
16000    100
Name: count, dtype: int64

Numero canali:
channels
1    100
Name: count, dtype: int64

17.14 — Ambiente per encoder Whisper

In [17]:
import torch
import transformers

print(
    "PyTorch:",
    torch.__version__
)

print(
    "Transformers:",
    transformers.__version__
)

print(
    "CUDA disponibile:",
    torch.cuda.is_available()
)

print(
    "Device scelto:",
    "cuda" if torch.cuda.is_available() else "cpu"
)

PyTorch: 2.13.0+cpu
Transformers: 5.14.1
CUDA disponibile: False
Device scelto: cpu

 17.15 — Caricamento encoder Whisper-small

In [18]:
import time
import torch

from transformers import (
    WhisperFeatureExtractor,
    WhisperModel
)


AUDIO_MODEL_NAME = "openai/whisper-small"

AUDIO_DEVICE = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)


print("Modello audio:", AUDIO_MODEL_NAME)
print("Device:", AUDIO_DEVICE)


start_time = time.time()


whisper_feature_extractor = (
    WhisperFeatureExtractor.from_pretrained(
        AUDIO_MODEL_NAME
    )
)


whisper_model = (
    WhisperModel.from_pretrained(
        AUDIO_MODEL_NAME
    )
)

whisper_model = whisper_model.to(
    AUDIO_DEVICE
)

whisper_model.eval()


print(
    "\nModello caricato in:",
    round(
        time.time() - start_time,
        2
    ),
    "secondi"
)

print(
    "Dimensione embedding encoder:",
    whisper_model.config.d_model
)

Modello audio: openai/whisper-small
Device: cpu

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

Modello caricato in: 1.96 secondi
Dimensione embedding encoder: 768

17.16 — Funzioni embedding Whisper turn-level

In [19]:
import soundfile as sf
import numpy as np


WHISPER_SR = 16000
WHISPER_MAX_SECONDS = 30.0
WHISPER_MAX_SAMPLES = int(
    WHISPER_SR
    * WHISPER_MAX_SECONDS
)


def load_audio_file(path):

    audio, sr = sf.read(
        str(path),
        dtype="float32"
    )

    if audio.ndim > 1:
        audio = audio.mean(axis=1)

    if sr != WHISPER_SR:
        raise ValueError(
            f"Sample rate inatteso: {sr}"
        )

    return audio


def split_audio_30s(audio):

    return [
        audio[start:start + WHISPER_MAX_SAMPLES]
        for start in range(
            0,
            len(audio),
            WHISPER_MAX_SAMPLES
        )
    ]


def whisper_embedding_batch(
    audio_list
):

    inputs = (
        whisper_feature_extractor(
            audio_list,
            sampling_rate=WHISPER_SR,
            return_tensors="pt"
        )
    )


    input_features = (
        inputs["input_features"]
        .to(AUDIO_DEVICE)
    )


    with torch.inference_mode():

        encoder_output = (
            whisper_model.encoder(
                input_features=input_features,
                return_dict=True
            )
            .last_hidden_state
        )


    hidden_length = (
        encoder_output.shape[1]
    )


    embeddings = []


    for i, audio in enumerate(
        audio_list
    ):

        # Whisper produce circa 50 frame encoder/sec.
        # Determiniamo quanti frame corrispondono
        # realmente all'audio, escludendo il padding.

        valid_ratio = min(
            len(audio)
            / WHISPER_MAX_SAMPLES,
            1.0
        )


        valid_frames = max(
            1,
            int(
                np.ceil(
                    hidden_length
                    * valid_ratio
                )
            )
        )


        emb = (
            encoder_output[
                i,
                :valid_frames,
                :
            ]
            .mean(dim=0)
            .cpu()
            .numpy()
        )


        embeddings.append(
            emb
        )


    return np.vstack(
        embeddings
    )

17.17 — Smoke test su 4 turni

In [20]:
test_df = (
    multimodal_df[
        multimodal_df[
            "turn_duration_seconds"
        ] <= 30
    ]
    .sample(
        n=4,
        random_state=42
    )
)


test_audio = [
    load_audio_file(path)
    for path in test_df[
        "audio_path_turn"
    ]
]


start = time.time()


test_embeddings = (
    whisper_embedding_batch(
        test_audio
    )
)


elapsed = (
    time.time()
    - start
)


print(
    "Shape:",
    test_embeddings.shape
)

print(
    "NaN:",
    np.isnan(
        test_embeddings
    ).sum()
)

print(
    "Inf:",
    np.isinf(
        test_embeddings
    ).sum()
)

print(
    "Tempo 4 turni:",
    round(elapsed, 2),
    "secondi"
)

Shape: (4, 768)
NaN: 0
Inf: 0
Tempo 4 turni: 9.97 secondi

17.18 — Benchmark CPU su 20 turni

In [21]:
BENCHMARK_N = 20


benchmark_df = (
    multimodal_df[
        multimodal_df[
            "turn_duration_seconds"
        ] <= 30
    ]
    .sample(
        n=BENCHMARK_N,
        random_state=123
    )
)


benchmark_audio = [
    load_audio_file(path)
    for path in benchmark_df[
        "audio_path_turn"
    ]
]


BATCH_SIZE = 4

benchmark_embeddings = []


start = time.time()


for start_idx in range(
    0,
    BENCHMARK_N,
    BATCH_SIZE
):

    batch_audio = (
        benchmark_audio[
            start_idx:
            start_idx + BATCH_SIZE
        ]
    )


    batch_emb = (
        whisper_embedding_batch(
            batch_audio
        )
    )


    benchmark_embeddings.append(
        batch_emb
    )


elapsed = (
    time.time()
    - start
)


benchmark_embeddings = (
    np.vstack(
        benchmark_embeddings
    )
)


seconds_per_turn = (
    elapsed
    / BENCHMARK_N
)


estimated_minutes = (
    seconds_per_turn
    * len(multimodal_df)
    / 60
)


print(
    "Shape benchmark:",
    benchmark_embeddings.shape
)

print(
    "Tempo totale:",
    round(elapsed, 2),
    "secondi"
)

print(
    "Secondi per turno:",
    round(seconds_per_turn, 3)
)

print(
    "Stima per 3710 turni:",
    round(estimated_minutes, 1),
    "minuti"
)

print(
    "Stima in ore:",
    round(
        estimated_minutes / 60,
        2
    )
)

Shape benchmark: (20, 768)
Tempo totale: 51.27 secondi
Secondi per turno: 2.563
Stima per 3710 turni: 158.5 minuti
Stima in ore: 2.64

 17.19 — Estrazione completa embedding audio Whisper-small con checkpoint e possibilità di resume

In [ ]:
from tqdm.auto import tqdm
import numpy as np
import time


AUDIO_EMBEDDING_PATH = (
    EMBEDDING_DIR
    / "embedding_audio_whisper_small_turn_level.npy"
)

AUDIO_PROGRESS_PATH = (
    EMBEDDING_DIR
    / "embedding_audio_whisper_small_progress.csv"
)


N_TURNS = len(multimodal_df)
EMBED_DIM = whisper_model.config.d_model
BATCH_SIZE = 4
CHECKPOINT_EVERY = 100


# ------------------------------------------------------------
# Eventuale resume
# ------------------------------------------------------------

if AUDIO_EMBEDDING_PATH.exists():

    audio_embeddings = np.load(
        AUDIO_EMBEDDING_PATH
    )

    if audio_embeddings.shape != (
        N_TURNS,
        EMBED_DIM
    ):
        raise ValueError(
            "Il checkpoint esistente ha shape inattesa: "
            f"{audio_embeddings.shape}"
        )

    print(
        "Checkpoint trovato."
    )

else:

    audio_embeddings = np.full(
        (
            N_TURNS,
            EMBED_DIM
        ),
        np.nan,
        dtype=np.float32
    )

    print(
        "Nuova estrazione."
    )


already_done = (
    ~np.isnan(
        audio_embeddings
    ).any(axis=1)
)


print(
    "Già completati:",
    int(already_done.sum()),
    "/",
    N_TURNS
)

Nuova estrazione.
Già completati: 0 / 3710

17.20 — Estrazione

In [23]:
def embedding_for_long_audio(audio):

    chunks = split_audio_30s(audio)
    chunk_embeddings = []
    chunk_weights = []

    for chunk in chunks:

        emb = whisper_embedding_batch(
            [chunk]
        )[0]

        chunk_embeddings.append(
            emb
        )

        chunk_weights.append(
            len(chunk)
        )

    chunk_embeddings = np.vstack(
        chunk_embeddings
    )

    chunk_weights = np.asarray(
        chunk_weights,
        dtype=float
    )

    return np.average(
        chunk_embeddings,
        axis=0,
        weights=chunk_weights
    ).astype(np.float32)


start_total = time.time()

pending_indices = np.where(
    ~already_done
)[0]


processed_since_save = 0


with tqdm(
    total=N_TURNS,
    initial=int(already_done.sum()),
    desc="Whisper turn-level"
) as pbar:

    position = 0

    while position < len(pending_indices):

        idx = pending_indices[position]

        duration = multimodal_df.loc[
            idx,
            "turn_duration_seconds"
        ]


        # ----------------------------------------------------
        # Caso raro: turno > 30 secondi
        # ----------------------------------------------------

        if duration > 30:

            audio = load_audio_file(
                multimodal_df.loc[
                    idx,
                    "audio_path_turn"
                ]
            )

            audio_embeddings[idx] = (
                embedding_for_long_audio(
                    audio
                )
            )

            position += 1
            processed_since_save += 1
            pbar.update(1)


        # ----------------------------------------------------
        # Turni <= 30 s: batch
        # ----------------------------------------------------

        else:

            batch_indices = []

            while (
                position < len(pending_indices)
                and
                len(batch_indices) < BATCH_SIZE
            ):

                candidate_idx = (
                    pending_indices[
                        position
                    ]
                )

                candidate_duration = (
                    multimodal_df.loc[
                        candidate_idx,
                        "turn_duration_seconds"
                    ]
                )

                if candidate_duration > 30:
                    break

                batch_indices.append(
                    candidate_idx
                )

                position += 1


            if len(batch_indices) == 0:
                continue


            batch_audio = [
                load_audio_file(
                    multimodal_df.loc[
                        i,
                        "audio_path_turn"
                    ]
                )
                for i in batch_indices
            ]


            batch_embeddings = (
                whisper_embedding_batch(
                    batch_audio
                )
            )


            for i, emb in zip(
                batch_indices,
                batch_embeddings
            ):

                audio_embeddings[i] = (
                    emb.astype(
                        np.float32
                    )
                )


            processed_since_save += (
                len(batch_indices)
            )

            pbar.update(
                len(batch_indices)
            )


        # ----------------------------------------------------
        # Checkpoint
        # ----------------------------------------------------

        if (
            processed_since_save
            >= CHECKPOINT_EVERY
        ):

            np.save(
                AUDIO_EMBEDDING_PATH,
                audio_embeddings
            )

            completed_now = (
                ~np.isnan(
                    audio_embeddings
                ).any(axis=1)
            )

            pd.DataFrame(
                {
                    "turn_id":
                        multimodal_df[
                            "turn_id"
                        ],

                    "completed":
                        completed_now
                }
            ).to_csv(
                AUDIO_PROGRESS_PATH,
                index=False
            )

            processed_since_save = 0


# ------------------------------------------------------------
# Salvataggio finale
# ------------------------------------------------------------

np.save(
    AUDIO_EMBEDDING_PATH,
    audio_embeddings
)


completed_final = (
    ~np.isnan(
        audio_embeddings
    ).any(axis=1)
)


pd.DataFrame(
    {
        "turn_id":
            multimodal_df[
                "turn_id"
            ],

        "completed":
            completed_final
    }
).to_csv(
    AUDIO_PROGRESS_PATH,
    index=False
)


elapsed_total = (
    time.time()
    - start_total
)


print("\nEstrazione terminata.")

print(
    "Completati:",
    int(completed_final.sum()),
    "/",
    N_TURNS
)

print(
    "Tempo totale:",
    round(
        elapsed_total / 60,
        1
    ),
    "minuti"
)

print(
    "File:",
    AUDIO_EMBEDDING_PATH
)

Whisper turn-level:   0%|          | 0/3710 [00:00<?, ?it/s]

Estrazione terminata.
Completati: 3710 / 3710
Tempo totale: 174.4 minuti
File: C:\Users\acer\Desktop\ProgettoTesi\risultati\embedding_multimodali_turn_level\embedding_audio_whisper_small_turn_level.npy

17.21 — QC embedding audio

In [24]:

audio_embeddings_final = np.load(
    AUDIO_EMBEDDING_PATH
)


print(
    "Shape:",
    audio_embeddings_final.shape
)

print(
    "NaN:",
    int(
        np.isnan(
            audio_embeddings_final
        ).sum()
    )
)

print(
    "Inf:",
    int(
        np.isinf(
            audio_embeddings_final
        ).sum()
    )
)

print(
    "Turni:",
    len(multimodal_df)
)

print(
    "Pazienti:",
    multimodal_df[
        "patient_id"
    ].nunique()
)

Shape: (3710, 768)
NaN: 0
Inf: 0
Turni: 3710
Pazienti: 90

17.22 — Early fusion audio + testo

In [ ]:
from sklearn.preprocessing import normalize
import numpy as np


# Controllo allineamento
assert audio_embeddings_final.shape[0] == text_embeddings.shape[0]
assert audio_embeddings_final.shape[0] == len(multimodal_df)


# Normalizzazione L2 separata delle due modalità
audio_embeddings_l2 = normalize(
    audio_embeddings_final,
    norm="l2"
).astype(np.float32)


text_embeddings_l2 = normalize(
    text_embeddings,
    norm="l2"
).astype(np.float32)

# Equal-weight early fusion
# Ogni blocco viene moltiplicato per 1/sqrt(2): in questo modo audio e testo contribuiscono in modo bilanciato alla norma complessiva.
MODALITY_WEIGHT = 1 / np.sqrt(2)


fusion_embeddings = np.concatenate(
    [
        MODALITY_WEIGHT * audio_embeddings_l2,
        MODALITY_WEIGHT * text_embeddings_l2
    ],
    axis=1
).astype(np.float32)


print(
    "Audio:",
    audio_embeddings_l2.shape
)

print(
    "Testo:",
    text_embeddings_l2.shape
)

print(
    "Fusion:",
    fusion_embeddings.shape
)


print(
    "\nNaN fusion:",
    int(np.isnan(fusion_embeddings).sum())
)

print(
    "Inf fusion:",
    int(np.isinf(fusion_embeddings).sum())
)

Audio: (3710, 768)
Testo: (3710, 384)
Fusion: (3710, 1152)

NaN fusion: 0
Inf fusion: 0

17.23 — QC normalizzazione e fusione

In [ ]:
audio_norms = np.linalg.norm(
    audio_embeddings_l2,
    axis=1
)

text_norms = np.linalg.norm(
    text_embeddings_l2,
    axis=1
)

fusion_norms = np.linalg.norm(
    fusion_embeddings,
    axis=1
)


print(
    "Norma audio media:",
    audio_norms.mean()
)

print(
    "Norma testo media:",
    text_norms.mean()
)

print(
    "Norma fusion media:",
    fusion_norms.mean()
)


print(
    "\nRange norma fusion:",
    fusion_norms.min(),
    "-",
    fusion_norms.max()
)

Norma audio media: 1.0
Norma testo media: 1.0
Norma fusion media: 1.0

Range norma fusion: 0.9999997 - 1.0000001

17.24 — Salvataggio delle tre rappresentazioni

In [ ]:
AUDIO_L2_PATH = (
    EMBEDDING_DIR
    / "embedding_audio_whisper_small_l2.npy"
)

TEXT_L2_PATH = (
    EMBEDDING_DIR
    / "embedding_testuali_multilingual_minilm_l2.npy"
)

FUSION_PATH = (
    EMBEDDING_DIR
    / "embedding_fusion_audio_testo_early_equal_weight.npy"
)


np.save(
    AUDIO_L2_PATH,
    audio_embeddings_l2
)

np.save(
    TEXT_L2_PATH,
    text_embeddings_l2
)

np.save(
    FUSION_PATH,
    fusion_embeddings
)


print("File salvati:")

for path in [
    AUDIO_L2_PATH,
    TEXT_L2_PATH,
    FUSION_PATH
]:

    print(
        "-",
        path.name,
        "->",
        path.exists()
    )

File salvati:
- embedding_audio_whisper_small_l2.npy -> True
- embedding_testuali_multilingual_minilm_l2.npy -> True
- embedding_fusion_audio_testo_early_equal_weight.npy -> True

17.25 — Audit finale

In [ ]:
FINAL_EMBEDDINGS = {
    "audio_raw": AUDIO_EMBEDDING_PATH,
    "audio_l2": AUDIO_L2_PATH,
    "text_raw": TEXT_EMBEDDING_PATH,
    "text_l2": TEXT_L2_PATH,
    "fusion_early": FUSION_PATH,
    "metadata": TEXT_METADATA_PATH
}

audit_rows = []

for name, path in FINAL_EMBEDDINGS.items():
    audit_rows.append(
        {
            "representation": name,
            "exists": path.exists(),
            "file": path.name
        }
    )

audit_embedding_df = pd.DataFrame(
    audit_rows
)

display(audit_embedding_df)

assert audit_embedding_df["exists"].all()

print(
    "\n✓ Notebook 17 completato."
)

print(
    "Turni comuni:",
    len(multimodal_df)
)

print(
    "Pazienti:",
    multimodal_df["patient_id"].nunique()
)

  representation  exists                                               file
0      audio_raw    True       embedding_audio_whisper_small_turn_level.npy
1       audio_l2    True               embedding_audio_whisper_small_l2.npy
2       text_raw    True         embedding_testuali_multilingual_minilm.npy
3        text_l2    True      embedding_testuali_multilingual_minilm_l2.npy
4   fusion_early    True  embedding_fusion_audio_testo_early_equal_weigh...
5       metadata    True                     metadata_turni_multimodali.csv

✓ Notebook 17 completato.
Turni comuni: 3710
Pazienti: 90